### ISSUE TITLE
Display Roku version along with IP:port

### ISSUE THREAD

**Issue by phillijw** [ncmiller/roku-cli#1]
When choosing a roku, I really don't plan on memorizing IP addresses. I do however know what version each of my roku devices is. If there is a way, could the version be shown as well?

**Comment by ncmiller** [comment]
Thanks for the suggestion. This requires a new feature in the python-roku library, so I've submitted a pull request (jcarbaugh/python-roku/pull/9). Once it's merged in, I will display something like this in the discovery phase:
`[1]   192.168.1.118:8060 Roku 3-4200X`
