### ISSUE TITLE
Feature Request  - Volume

### ISSUE THREAD

**Issue by tmanok** [ncmiller/roku-cli#4]
Excellent program! Loving it. 
One missing item: volumeup or volumedown. 

Getting by with: 
```
#!/bin/bash
curl -d '' http://192.168.0.x:8060/keypress/$1
```
And then summoning it with an example input: `roku.sh volumeup`

If this could be instead added to the python program, that would be radicalistic!
Cheers,

Tmanok

**Comment by ncmiller** [comment]
Thanks @tmanok.

This seems like a straightforward feature to add, so I'll look into it.

**Comment by tmanok** [comment]
Awesome thank you so much :D

**Comment by ncmiller** [comment]
@tmanok - I've added support for volume control in this PR: https://github.com/ncmiller/roku-cli/pull/5.

I don't have a Roku TV, so I was unable to test the actual volume control aspect, but I think it should work.

Can you pull the branch from that PR and see if it works on your Roku TV? 

```
git fetch
git checkout nick/volume_control
python setup.py install
```

**Comment by tmanok** [comment]
Luckily I have a fresh Ubuntu VM that I could test on my laptop (with access to my Roku) for you. 
Snapshotted VM because it won't need to run anything to do with roku-cli later...

```
sudo apt update; sudo apt install git python python3-pip curl -y
git clone https://github.com/ncmiller/roku-cli.git
cd roku.cli
git fetch origin pull/5/head:pr-5
git checkout nick/volume_control
```

Snapshotted VM in case my next steps became a mistake. 

```
python setup.py install 
_'importerror no module named setuptools'_
sudo apt install python3-setuptools
_'already installed...'_
pip3 install -U pip setuptools.py
_'Missing dependency testresources for some library, oh and you're missing /home/user/.local/bin in your path'_
python setup.py install 
_'importerror no module named setuptools'_
export PATH=$PATH:/home/user/.local/bin ; pip3 install testresources pip setuptools
python setup.py install 
_'importerror no module named setuptools'_
```

That's where I'm at. Please let me know if I've made a critical mistake anywhere, it seems like I've goofed my fresh Ubuntu system's python somewhere. 
Cheers,


Tmanok

**Comment by ncmiller** [comment]
@tmanok - Thanks for taking the time to try it. 

It seems like maybe a python2 vs 3 issue (what does `python -V` give you?) or maybe some kind of `PYTHON_PATH` issue. I probably won't be much help here beyond what Google offers.

I'm going to go ahead and merge the PR and release to PyPi as version 1.0.5. I've tested as far as I can without a Roku TV, so I'm pretty confident it will work. If there's an issue, I can release another version to fix it.

**Comment by ncmiller** [comment]
@tmanok - I uploaded version `1.0.6` to PyPI with support for volume control.

You can try it out:

```
pip install --upgrade rokucli
```

I'm going to go ahead and close this issue since the feature has been added. If you encounter any problems with volume control, then please open another issue.

**Comment by tmanok** [comment]
Hey NCMiller,

You were correct:
`python3 setup.py install`
Passed the error, however I think it later disliked that the pull request had been completed. 

Purged and installed rokucli using pip3, works with volume control now. Nice touch with muting! Also tested upgrading using `pip3 install -U rokucli` on my laptop's Linux Mint, works perfectly as expected. Thanks!


Tmanok

**Comment by ncmiller** [comment]
@tmanok - Awesome, glad to hear it 👍
