### ISSUE TITLE
possible to change key bindings?

### ISSUE THREAD

**Issue by mptpro** [ncmiller/roku-cli#6]
Fantastic program - I use it daily!

Is it possible to change the ky bindings, such as up-arrow-key = volume up, or the reverse?

**Comment by ncmiller** [comment]
Hi @mptpro - yeah, it's possible.

I think for the default values, I'll probably want to leave those the same, where the up and down arrows are used for navigation up and down.

If you want to use up/down arrow for volume control, I would recommend one of the following options:

1. In your local checkout of the repo, modify the key mapping here: https://github.com/ncmiller/roku-cli/blob/master/rokucli/cli.py#L141. 
2. Same as above, but fork this repo and make the changes in your fork.

There is maybe a future where code is added for overriding defaults via a user config file (e.g. `keymap.json`), but I will probably hold off on that until there is a real need.

**Comment by mptpro** [comment]
sounds good. Thanks and thank you for this great program!

**Comment by ncmiller** [comment]
:+1: Thanks for the kind words.
